title: Красноармейская, 16
description: Информационный сайт дома в Ульяновске
email: ms.toneryan@gmail.com
baseurl: ""
url: "https://k16.gongled.ru"
lang: ru
encoding: utf-8

# Build settings
markdown: kramdown

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Sass settings
sass:
    style: :compressed

analytics:
  google:
    tracking_code: UNKNOWN
  yandex:
    tracking_code: UNKNOWN

contacts:
  address: г. Ульяновск, ул. Красноармейская, 16
  leader: Тонерян Мкртыч Саркисович
  work_phone: 79084739746
  personal_phone: 79084739746
  email: inbox@ms.toneryan@gmail.com
  webmaster_email: inbox@gongled.ru
  github_url: https://github.com/gongled/k16ul

links:
  project: "https://k16.kaiten.ru/p/396805f7-7ed6-466d-98f8-fd1aa4c37664"

paginate: 5
paginate_path: "/article/page:num/"

# Collections
collections:
  pages:
    output: true
    permalink: :path

# Defaults
defaults:
  - scope:
      type: posts
    values:
      layout: post
      permalink: /article/:year/:month/:day/:title.html
  - scope:
      type: pages
    values:
      layout: page

exclude: [vendor, deploy.yml, environments, Gemfile, Gemfile.lock, Makefile, README.md, deploy.retry, Dockerfile, docker-compose.yml, ansible.cfg]
